apiVersion: v1
kind: Namespace
metadata:
  name: dhcp-system

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dhcp
  namespace: dhcp-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kube-dhcp
    spec:
      hostNetwork: true
      containers:
      - name: server
        imagePullPolicy: IfNotPresent
        image: kube-dhcp
        env:
        - name: METADATA_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METADATA_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: METADATA_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
