apiVersion: v1
kind: Namespace
metadata:
  name: dhcp-system

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-dhcp-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-dhcp-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-dhcp-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: dhcp-system

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dhcp
  namespace: dhcp-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kube-dhcp
    spec:
      hostNetwork: true
      containers:
      - name: server
        imagePullPolicy: IfNotPresent
        image: pulcy/kube-dhcp@sha256:adc24ec063a43e51d25d77975ff999066db8720708bc33ea66311afdaa1ca2ef
        env:
        - name: METADATA_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METADATA_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: METADATA_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
