apiVersion: v1
kind: Namespace
metadata:
  name: dhcp-system

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: leases.dhcp.pulcy.com
spec:
  group: dhcp.pulcy.com
  version: v1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    plural: leases
    singular: lease
    kind: Lease
    shortNames:
      - dl

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-dhcp-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  verbs:
  - "*"
- apiGroups:
  - dhcp.pulcy.com
  resources:
  - leases
  verbs:
  - "*"
  
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-dhcp-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-dhcp-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: dhcp-system

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dhcp
  namespace: dhcp-system
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: kube-dhcp
    spec:
      hostNetwork: true
      containers:
      - name: server
        imagePullPolicy: IfNotPresent
        image: pulcy/kube-dhcp-arm64@sha256:e5581b1998892c36c3295e9dbf8eecc92187f5549f1a94b3b6b7b231dd66a8fc
        env:
        - name: METADATA_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METADATA_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: METADATA_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
