apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dhcp-system
  name: kube-dhcp-config
data:
  config: |
    # Address of the server itself
    server-ip: 192.168.10.2
    # List of address ranges
    ranges:
    - start: 192.168.10.20
      length: 10
    # DHCP options
    options:
      dns-ip: 192.168.10.2
      router-ip: 192.168.10.1
      subnet-mask: 255.255.255.0
